export const RECIPES_LOADED = "RECIPES_LOADED";
export const RECIPE_LOADED = "RECIPE_LOADED";
export const RECIPE_CREATED = "RECIPE_CREATED";
export const RECIPE_EDITED = "RECIPE_EDITED";
export const RECIPE_DELETED = "RECIPE_DELETED";
